### ISSUE TITLE
Get Involved -> Volunteer

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/smartmaps#18]
### Purpose

There should be a page for volunteers to sign-up to help with the group!

**Comment by hfu** [comment]
Thank you @albertkun. Because I really like this, I updated https://github.com/UNopenGIS/smartmaps/blob/main/i18n/ja/docusaurus-plugin-content-docs/current/get-involved/volunteer/document-content-volunteer.md to look even more natural Japanese language. I am sharing this with my friends now to see what happens. It is very exciting because this would be the first time for Smart Maps Group to recruit volunteers in such an open style 🎉.
