### ISSUE TITLE
📝 Design Flier for Guest Speakers

### ISSUE THREAD

**Issue by albertkun** [UNopenGIS/smartmaps#33]
### Purpose
To be used on social media and the documentation website.

@lindseymardona is volunteering for it!

**Comment by hfu** [comment]
@albertkun and @lindseymardona, many thanks for the draft flyer!

- I like the country time codes because it would be more practical. 
- I see the beauty of the simplicity of "Asia" instead of "Monthly" (ah, this event is Monthly rather than Querterly. Quarterly is on 2023-08-09). 
- I prefer "Pacific" rather than "Asia" because it will make clear that California / Los Angeles are surely included in the zone. I also notice that this choice of time is not so convenient for West Asian colleagues, that is another reason why I prefer Pacific. 
- Also, we can call Quarterly simply as Atlantic rather than "US East Coast / Europe / Africa". So, my choice of words are either "Monthly/Quarterly" or "Pacific/Atlantic". 

What do you think? 

I also love the color scheme!

**Comment by albertkun** [comment]
@hfu Thank you for your feedback! I passed it over to @lindseymardona!

- I agree that the country codes are more practical!
- I also agree with putting the region in focus (Asia)
- Good point about keeping the west coast and western Asia not being covered! How does `Asia Pacific` sound? If not, I think I prefer `Pacific/Atlantic` over Monthly/Quarterly`!

I am glad you like the color scheme! The red color that @lindseymardona chose was great! She did ask if there was a `.svg` or transparent version of the logo, since she had to manually make it transparent in Photoshop it doesn't look as clean.

**Comment by hfu** [comment]
@albertkun Thanks. Then how about using **Asia Pacific** while keeping **Atlantic** on hold? Maybe we might find a good replacement of Atlantic in future, but we use **Asia Pacific / Atlantic** pair tentatively. 

Regarding the logo, attached is the best version of what I have. Maybe we can develop the official SVG logo from this file with @lindseymardona. 

[7-logo.pptx](https://github.com/UNopenGIS/smartmaps/files/12266005/7-logo.pptx)

**Comment by hfu** [comment]
In reality, `Atlantic` is `HQ` in a practical sense. We have the quarterly meetup to meet with our colleagues in 1) UNHQ, 2) UN Global Service Centre, and 3) UN Peacekeeping Missions. 9am in NY / 3pm in Rome is a kind of standard time for such meetings.

Because `Asia Pacific` is a UN Term, if we are choosing UN Terms, it may be `Americas / Europe / Africas`. 

See also: https://unterm.un.org/unterm2/en/

**Comment by hfu** [comment]
By the way, I am already using the color scheme in the upcoming presentation! 

<img width="972" alt="スクリーンショット 2023-08-05 12 47 21" src="https://github.com/UNopenGIS/smartmaps/assets/18297/557cbda5-0acc-4b6c-bdf4-20374983504e">

Huge thanks to @lindseymardona and @albertkun!

**Comment by albertkun** [comment]
> @albertkun Thanks. Then how about using **Asia Pacific** while keeping **Atlantic** on hold? Maybe we might find a good replacement of Atlantic in future, but we use **Asia Pacific / Atlantic** pair tentatively.
> 
> Regarding the logo, attached is the best version of what I have. Maybe we can develop the official SVG logo from this file with @lindseymardona.
> 
> [7-logo.pptx](https://github.com/UNopenGIS/smartmaps/files/12266005/7-logo.pptx)

Oh, very good points! I do like the simplicity of `Asia Pacific`, but I can see how that could cause confusion with the official UN terms. How does `Indo-Pacific` sound? https://en.wikipedia.org/wiki/Indo-Pacific 🤣 Otherwise, I think just keeping it as `Pacific` works!

Thank you for the `.pptx` of the 7! Would you happen to know where we could find the SVG of the UN Open GIS logo?

**Comment by albertkun** [comment]
> By the way, I am already using the color scheme in the upcoming presentation!
> <img alt="スクリーンショット 2023-08-05 12 47 21" width="972" src="https://user-images.githubusercontent.com/18297/258561161-557cbda5-0acc-4b6c-bdf4-20374983504e.png">
> 
> Huge thanks to @lindseymardona and @albertkun!

Ohh, that's so great! I'm glad to see that you are using it!! Just a little feedback though:

That's so great to see you using the colors already!! It makes us both really glad!! 

For the purposes of your slides, the blue works well as the focus for `practice` primary color! 

We can discuss this later, in #36, but I was thinking in general practice we can use blue for principles/identity and red for practice! This is based on how blue is the UN color, so that can represent our larger group/broader goals- as well as being the primary color.

**Comment by hfu** [comment]
@albertkun Many thanks for your inputs!

## Color scheme
@albertkun Thank you for reviewing the use of color scheme. I see your poin in using **blue for principles and red for practice**. It would be better. I will update my slides accordingly. 

## UN Open GIS logo
UN Open GIS logo gives us headaches several times. (See also: https://github.com/UNopenGIS/7/issues/115#issuecomment-1590145748) Maybe we can volunteer to create a SVG version of the UN Open GIS logo. What do you think? 

Maybe we can have a plan to start from https://commons.wikimedia.org/wiki/File:Logo_of_the_United_Nations.svg and consult with UN Geospatial Information Section for their advice. 

Maybe we should create a separate issue regarding UN Open GIS logo. 

## Asia, Asia Pacific, Pacific, or Indo-Pacific
Thank you for your consideration about the choice of word from Asia, Asia Pacific, Pacific, or even Indo-Pacific. 

I am +1 for Pacific because it is simple. Also, if we think about ocean drainage, use of Pacific / Atlantic seems correctly reflecting the current distribution of currently active contributors. 

![ocean drainage](https://upload.wikimedia.org/wikipedia/commons/b/b1/Ocean_drainage.png)

Figure above is https://upload.wikimedia.org/wikipedia/commons/b/b1/Ocean_drainage.png

If we have more friends contributing from Indian ocean drainage area, we may need to have another arrangement of online meeting and that can be called Smart Maps Meetup Indian (ocean), depending on how we choose a right time for a meeting. 

Maybe we decide to use Pacific for the time being, and continuously consider a better name depending on who are participating.

**Comment by albertkun** [comment]
@hfu Thank you for the feedback!

### Color Scheme
We can definitely be flexible! But, I think the way your slides adopted the color scheme is amazing!

### UN Open GIS logo
Thank you for pointing me to the svg file! I'll try to take a stab at creating it! I actually can do some work with Adobe Illustrator, so I will be attempting it over the week. 

I went ahead and made a separate issue to track this here:
https://github.com/UNopenGIS/7/issues/233

### Pacific

I agree with your response and we will use `Pacific` going forward! I also like that we can be flexible and modify the name accordingly depending on our active community!

**Comment by albertkun** [comment]
Quick update:

@lindseymardona and I will meet later today to finalize the flier, maybe it would be helpful to present it on https://github.com/UNopenGIS/7/issues/214 !

**Comment by hfu** [comment]
Yes, I will include the flier when available for https://github.com/unopengis/7/issues/214! 

I also start bureau internal consultatin regarding https://github.com/unopengis/7/issues/233.

**Comment by albertkun** [comment]
@hfu Great! We should have it complete by tonight at 3pm JST.

**Comment by albertkun** [comment]
@hfu here are the final fliers for our next meet up!

- Horizontal 

![unsmartmaps-flyer-aug-final](https://github.com/UNopenGIS/smartmaps/assets/8574425/84f7d874-289e-41a8-b60e-1d40201345a7)

- Vertical (for print)

![unsmartmaps-flyer-aug-vertical-final](https://github.com/UNopenGIS/smartmaps/assets/8574425/9c3be77f-a7ee-4a88-a204-10efcc14bb9d)

**Comment by hfu** [comment]
Huge thanks to @lindseymardona and @albertkun, I added the flier to slide 7 of the deck. 

![image](https://github.com/UNopenGIS/smartmaps/assets/18297/fe632ca9-14fa-4012-9280-b5a7b82fe201)

See: https://docs.google.com/presentation/d/1OwuZeywXDsbAmpsuYT3m70hp4psQag7O8nfHJZNzvrs/edit?usp=sharing

**Comment by albertkun** [comment]
@hfu Looks great and fits right in with the presentation!
